version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - rest-server
      - grpc-server

  rest-server:
    build:
      context: .
      dockerfile: rest-server/Dockerfile
    container_name: rest-server

  grpc-server:
    build:
      context: .
      dockerfile: grpc-server/Dockerfile
    container_name: grpc-server
