spring:
  application:
    name: client

grpc:
  client:
    grpc-server:
      address: "static://grpc-server:9090"
      negotiationType: plaintext

rest:
  client:
    rest-server:
      address: "http://rest-server:8081"

server:
  port: 8080
