spring:
  application:
    name: client

grpc:
  client:
    grpc-server:
      address: "static://grpc-server:9090"
      negotiationType: plaintext

rest:
  server:
    url: "http://grpc-server:8081"

server:
  http2:
    enabled: true
  port: 8080
